### ISSUE TITLE
parentID is incorrect and parentTable is empty (at least in parties_ids)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/spoonbill#105]
`parentID` should match the `rowID` in the parent table.

Tested with the `ocds-sample-data.json` fixture (`spoonbill tests/data/ocds-sample-data.json`).

**Comment by jpmckinney** [comment]
Also, `parentTable` is present but empty in `parties_ids`.

**Comment by yolile** [comment]
@sorenabell is this deployed and fixed in the web interface too?

**Comment by sorenabell** [comment]
@yolile yes, it is.

**Comment by yolile** [comment]
I see this is indeed working now in the website, thanks!
