### ISSUE TITLE
Human-friendly column  (from schema)

### ISSUE THREAD

**Issue by sorenabell** [open-contracting/spoonbill#110]
Use human-friendly titles for fields in the schema (in English and Spanish https://standard.open-contracting.org/latest/es/release-schema.json)
-----------------------

Since there are human-friendly titles for fields in the schema (in English and Spanish https://standard.open-contracting.org/latest/es/release-schema.json), we prefer to use those titles, instead of using Transifex to provide the human-friendly titles. As I understand, this was how it was originally implemented. In any case, I pre-approve this change request. cc 

In terms of implementation, when a child table is merged into a parent table, we will need to prefix the parent field’s title to the child field’s title, e.g. “Additional identifiers: ID” if party_ids is merged into parties.

**Comment by sorenabell** [comment]
@jpmckinney This implementation of the human-readable headers is based on extracting titles from schema one by one. For example, path `tenders/items/value/amount` would be named `Tender Item Value Amount`. Some grammar issues may be caused in other languages, e.g. Spanish headers, produced in such a way, may not be 100% correct from the grammatic point of view: `Licitación Artículo Valor Monto`, that's why i18n was implemented. 
Is this the correct approach? Should we merge our changes?

**Comment by yolile** [comment]
We discussed this with the team and it is ok to use the titles but separating them with ": " eg `Licitación: Artículo: Valor: Monto` (note the colons + blank space)

**Comment by jpmckinney** [comment]
We should have the same punctuation in English.

**Comment by sorenabell** [comment]
PR for this task is on review. Meanwhile, I wanted to share the resulting files we are expecting to have.
Please note, that in case when respective h/r title is not present in schema, it's left as it is, with applied formatting.

[resultEN.xlsx](https://github.com/open-contracting/spoonbill/files/6900266/resultEN.xlsx)
[resultES.xlsx](https://github.com/open-contracting/spoonbill/files/6900268/resultES.xlsx)

**Comment by jpmckinney** [comment]
@yolile Can you check the resultES.xlsx file above?

**Comment by yolile** [comment]
Looks good!

**Comment by jpmckinney** [comment]
English looks good, too! Thanks, @sorenabell 

English headings:

<details>

  1: ocid
  2: id
  3: rowID
  4: parentID
  5: Buyer: Organization name
  6: Buyer: Organization ID
  7: Parties: Common name
  8: Parties: Entity ID
  9: Parties: Party roles
 10: Parties: Contact point: Name
 11: Parties: Contact point: Email
 12: Parties: Contact point: Telephone
 13: Parties: Contact point: Fax number
 14: Parties: Contact point: URL
 15: Parties: Address: Street address
 16: Parties: Address: Locality
 17: Parties: Address: Region
 18: Parties: Address: Country name
 19: Parties: Additional identifiers: 0: Scheme
 20: Parties: Additional identifiers: 0: ID
 21: Parties: Additional identifiers: 0: Legal Name
 22: Parties: Identifier: Scheme
 23: Parties: Identifier: ID
 24: Parties: Identifier: Legal Name
 25: Parties: Details: Legal Entity Type Detail
 26: Parties: Details: Activity Types
 27: Parties: Details: Categories: Name
 28: Parties: Details: Categories: Id
 29: Parties: Details: Level
 30: Parties: Details: Entity Type
 31: Parties: Details: Type

</details>

Spanish headings:

<details>

  1: ocid
  2: id
  3: rowID
  4: parentID
  5: Comprador: Nombre de la Organización
  6: Comprador: ID de Organización
  7: Partes involucradas: Nombre común
  8: Partes involucradas: ID de Entidad
  9: Partes involucradas: Roles de las partes
 10: Partes involucradas: Punto de contacto: Nombre
 11: Partes involucradas: Punto de contacto: Correo electrónico
 12: Partes involucradas: Punto de contacto: Teléfono
 13: Partes involucradas: Punto de contacto: Número de fax
 14: Partes involucradas: Punto de contacto: URL
 15: Partes involucradas: Dirección: Dirección
 16: Partes involucradas: Dirección: Localidad
 17: Partes involucradas: Dirección: Región
 18: Partes involucradas: Dirección: País
 19: Partes involucradas: Identificadores adicionales: 0: Esquema
 20: Partes involucradas: Identificadores adicionales: 0: ID
 21: Partes involucradas: Identificadores adicionales: 0: Nombre Legal
 22: Partes involucradas: Identificador: Esquema
 23: Partes involucradas: Identificador: ID
 24: Partes involucradas: Identificador: Nombre Legal
 25: Partes involucradas: Detalles: Legal Entity Type Detail
 26: Partes involucradas: Detalles: Activity Types
 27: Partes involucradas: Detalles: Categories: Name
 28: Partes involucradas: Detalles: Categories: Id
 29: Partes involucradas: Detalles: Level
 30: Partes involucradas: Detalles: Entity Type
 31: Partes involucradas: Detalles: Type

</details>

**Comment by sorenabell** [comment]
@jpmckinney @yolile Please check the headings in the web application.

**Comment by yolile** [comment]
@sorenabell I tested it now, but I still got the old version of the titles, maybe the changes were not deployed yet?

**Comment by yolile** [comment]
Ok I tested it in the stage server, most of the things look good but I have the following comments:

1. Documents table: the tool is using "Planning: Planning Milestones: Milestones: Documents" as the header for the documents table
![docs_uru](https://user-images.githubusercontent.com/6834122/132740425-ea1bfed3-4ad2-4a78-9c12-56c919054036.png)

2. Awards suppliers: For the suppliers related columns the tool is using "Awards: Award: Suppliers: **Organization Reference**: Organization Name", but I think that this should be without "Organization Reference", similiar to Buyer, where we have "Buyer: Organization Name" and "Buyer: Organization ID" directly.
![suppliers](https://user-images.githubusercontent.com/6834122/132740586-f239216b-96b7-4e5c-afab-a35dab45d463.png)

3. Awards items: the tool is using the old version of the columns names when the document contains more than one item:
![awards_items](https://user-images.githubusercontent.com/6834122/132741055-ef7b6f40-bff5-4ca4-823a-e58fb51f994f.png)

Tested files:
[adjudicacion-584902.txt](https://github.com/open-contracting/spoonbill/files/7138886/adjudicacion-584902.txt)
[llamado-584681.txt](https://github.com/open-contracting/spoonbill/files/7138889/llamado-584681.txt)

**Comment by sorenabell** [comment]
@yolile , thank you for the feedback.

1. Indeed, the heading is wrong, we will fix it.
2. As far as I understood, there is a difference in those two cases in [schema](https://standard.open-contracting.org/latest/en/release-schema.json) that leads to differences in naming. `Suppliers` `Organization Reference` lacks `title`.

![image](https://user-images.githubusercontent.com/5451803/132873618-9510592f-5995-499f-b8cf-d18b1486aaef.png)
![image](https://user-images.githubusercontent.com/5451803/132873636-a3d6b96e-117f-4502-9b02-56d79749be24.png)

3. The fix is on the way.

**Comment by yolile** [comment]
@sorenabell thank you for the updates. Yes, 'suppliers' is an array of OrganizationReferece and 'buyer' is an OrganizationReferece itself. I think we can have a workaround for these cases but it is just a minor thing and I guess we can leave it as it is for now.

**Comment by sorenabell** [comment]
@yolile 
1. Document headers have been fixed, now each of them looks properly (starts with `Documents` and so on).
2. Currently, a workaround is in place - if the reference object in the schema has no title (like in particular case with 'supplier'), such title will be skipped and not included in the final header. But we are thinking about removing it in the next release. Please advise us here.
3. This deviation has been fixed as well, now all columns of an array have the same headers.

**Comment by yolile** [comment]
@sorenabell 

> But we are thinking about removing it in the next release.

I'm ok with removing it if it is too tricky, thanks!
