### ISSUE TITLE
CLI: read standart input

### ISSUE THREAD

**Issue by yshalenyk** [open-contracting/spoonbill#138]
It might be nice to have ability to read stdin to work with remote files.
For example something like
`wget -O - <url> | spoonbill`
or 
`wget -O - <url> | spoonbill -`

Or maybe concatenate multiple jsonl files
`cat jsonl1 jsonl2 | spoonbill`

**Comment by jpmckinney** [comment]
Hmm, wouldn't the data need to be stored temporarily, since it needs to be read twice (once for analysis, and again for flattening/writing)?

**Comment by jpmckinney** [comment]
I think there is not enough demand for this feature.
