### ISSUE TITLE
ocdsextensionregistry ProfileBuilder language choice option

### ISSUE THREAD

**Issue by sorenabell** [open-contracting/spoonbill#166]
Follow-up for #110.

Update ocdsextensionregistry to enable language choice option

**Comment by jpmckinney** [comment]
I think this is the same as #185

**Comment by jpmckinney** [comment]
Nevermind - this is for the language of the main schema.

**Comment by jpmckinney** [comment]
Similar to #185, we can defer to --schema, i.e. the user (or web tool) provides a schema that has been created by the ProfileBuilder. It would be nicer to handle this within Spoonbill, but there are already too many higher priority issues.
