### ISSUE TITLE
Percentage complete goes up to 690%

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/spoonbill#168]
See screen shot attached. The percentage complete appears to go over 100% when the file analysis process starts. 

The percentage complete needs to be 100% max.

<img width="706" alt="Screenshot 2021-07-16 112307" src="https://user-images.githubusercontent.com/11212467/127169234-6b4d6a05-15f6-45f7-a1a6-509ccf63c242.png">

**Comment by sorenabell** [comment]
Closed via https://github.com/open-contracting/spoonbill-web/pull/317

**Comment by sabahfromlondon** [comment]
Tested, this is much better now. Thank you

**Comment by sorenabell** [comment]
It happened because the example file is an archive and the extracted file has a bigger size than the archive itself. Now we just take the size of the extracted file for the percentage calculation.
