### ISSUE TITLE
FAQ box on upload file screen has a different design

### ISSUE THREAD

**Issue by sabahfromlondon** [open-contracting/spoonbill#169]
I think the design for the FAQs should be consistent. The FAQ box on the upload page doesn't have text in the heading or the questions:

Upload screen box:
<img width="222" alt="Screenshot 2021-07-27 153228" src="https://user-images.githubusercontent.com/11212467/127178524-739dabfe-c247-4b41-9474-6c0ec40b8dea.png">

Select data box 
<img width="220" alt="Screenshot 2021-07-27 153252" src="https://user-images.githubusercontent.com/11212467/127178446-374b79f2-651e-49ab-8dc1-f8c4d9ad1758.png">

I'm not sure how, but we sees to have lost the questions on the upload screen from the initial UX design:

<img width="443" alt="Screenshot 2021-07-27 160229" src="https://user-images.githubusercontent.com/11212467/127178248-ad93c667-758e-43d3-9f28-ca87e2482ca4.png">

To do:
- Add FAQ to heading of the box on the upload page
- Update the content to that provided below 
- Have line breaks between the paragraphs for the answers
- Keep the links for the Command Line tool (https://flatten-tool.readthedocs.io/en/latest/usage-ocds/) and the Data Review Tool (https://standard.open-contracting.org/review/)

-------------------------------

**How do I convert CSV or Excel data to JSON?**
If you would like to convert CSV data to JSON, please use the older Command-Line tool.

Please note that the Command-Line Tool requires some knowledge of programming and is not suited to non-technical users.

-------------------------------
**What should I do if there are issues with my file?**
The JSON data you upload should be in OCDS version 1.1 or 1.0, otherwise it may not be possible to flatten. 

If you are uncertain whether your data complies with OCDS, use the Data Review Tool to check first.
 
-------------------------------

**Comment by jpmckinney** [comment]
The link for the CLI should be https://open-contracting.github.io/spoonbill/

**Comment by sorenabell** [comment]
Closed via https://github.com/open-contracting/spoonbill-web/pull/315

**Comment by sabahfromlondon** [comment]
Looks good, thanks
