### ISSUE TITLE
Add GitHub workflows for linting and testing

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/spoonbill#18]
For the testing workflow, please integrate Coveralls (I've already configured things at coveralls.io). An example: https://github.com/open-contracting/ocds-merge/blob/main/.github/workflows/ci.yml#L27-L29

**Comment by pontostroy** [comment]
Repeats pre-commit step with black isort and etc on lint stage. After tests unload the file to coveralls
https://github.com/open-contracting/spoonbill/commit/8f0a242823995e8e28ed9661d08028cb88f446be
