### ISSUE TITLE
Extension schema support

### ISSUE THREAD

**Issue by sorenabell** [open-contracting/spoonbill#183]

**Comment by jpmckinney** [comment]
What work is needed for this support?

For example, I think get_schema and parse_schema (i.e. where ProfileBuilder is used) need to be made aware of any extensions declared in the data - but I'm not sure what else will need to change.

**Comment by jpmckinney** [comment]
I don't know if this is related to #205, but if so it is a bug rather than an enhancement.

**Comment by jpmckinney** [comment]
Since I don't know what this issue is about, I'll close it for the same reason as #184 #185 #166: I think we can defer to --schema, i.e. the user (or web tool) provides a schema that has been created by the ProfileBuilder.
