### ISSUE TITLE
Extension schema for JSON Lines format support

### ISSUE THREAD

**Issue by sorenabell** [open-contracting/spoonbill#184]

**Comment by jpmckinney** [comment]
How does this differ from #183? What is special about JSON Lines with respect to extensions?

**Comment by sorenabell** [comment]
JSON Lines does not contain information about extensions. A way to pass this information to the system is needed.

**Comment by jpmckinney** [comment]
Aha, of course :)

**Comment by jpmckinney** [comment]
I think `--schema` already handles this case.
