### ISSUE TITLE
Unique sheet names

### ISSUE THREAD

**Issue by yshalenyk** [open-contracting/spoonbill#43]
Shortening sheet names to fit 31 characters limit could possibly lead to generating duplicate names, so we need to add sheet number when this situation occurs.

**Comment by sabahfromlondon** [comment]
I'm not sure I understand. The sheet names will just be the names of the main tables (Parties, Planning, Tender...) so I don't expect any to go over the character limit. 

If the user renames a table, then we should limit how long the name can be via the UI.

**Comment by jpmckinney** [comment]
@yshalenyk I think the limit is 31 characters, not 35?

@sabahfromlondon For example, `transactions` is an array under the `implementation` object, under the `contracts` array. `contracts_implementation_transactions` is 38 characters. If there is an additional array field like `contracts_implementation_transactors`, then they will both truncate to `contracts_implementation_transa`. Similarly, if the data has additional fields, we can't predict what tables might be possible.

The old flatten tool had a configurable character length of each segment, e.g. it would create tables like `contracts_implement_transacti` if the segment length is set to 9.

@yshalenyk's proposal is to add numbers at the end, e.g. `contracts_implementation_trans1` and `contracts_implementation_trans2` in the above example.

Related #45

**Comment by sabahfromlondon** [comment]
Ok I've had a think about this and the suggestion of `contracts_implementation_trans1` and `contracts_implementation_trans2` looks like the best option.
