### ISSUE TITLE
Table names abbreviation

### ISSUE THREAD

**Issue by yshalenyk** [open-contracting/spoonbill#45]
Excel allows up to 31 characters.
Current algorithm abbreviates table names even their name is shorter which is not generally user friendly.

As a possible simplest solution we could abbreviate only names not fitting this limit.
This issue is a continuation of discussion in https://github.com/open-contracting/spoonbill-web/issues/100

**Comment by yshalenyk** [comment]
Another option I see we could try to create human friendly name, like `Tender Items` but its unclear which approach to chose to do it. As a one way is use existing table names as a table ids and create mapping between table id and table title, but is may create problems for data with extensions.

**Comment by yshalenyk** [comment]
@jpmckinney FYI

**Comment by jpmckinney** [comment]
@sabahfromlondon I have some ideas for handling edge cases, but what do you think should be the general approach?

**Comment by sabahfromlondon** [comment]
@jpmckinney 

Some options:

1. We can remove the the first word in the headings e.g. 'Planning Budget Amount Currency' can just be 'Budget Amount Currency' as the table is already referred to as 'Planning'. I think this will get around most of the issues, but perhaps not all.

2. We can abbreviate some of the words e.g. Minimum to Min., Enquiry to Enq., Tender to Ten. etc. I think most of these will be understandable to users.

**Comment by jpmckinney** [comment]
@sabahfromlondon This issue is about table/sheet names, not headings.

@yshalenyk I think we only need a few abbreviations for OCDS itself, for example, maybe these, if needed:

* contracts_implementation -> implementation
* contracts_implementation_transactions -> transactions
* additionalIdentifiers -> ids
* additionalClassifications -> class
* documents -> docs

**Comment by sabahfromlondon** [comment]
Ah yes, I thought this was about headings. My mistake sorry. 

Happy with your suggestions for abbreviations.
