### ISSUE TITLE
CLI: Warnings are very repetitive

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/spoonbill#73]
To reproduce:
```
curl https://opentender.eu/data/files/AT_ocds_data.json.tar.gz
tar xvf AT_ocds_data.json.tar.gz
cat AT_ocds_data.json ocdskit combine-release-packages > release_package.json
spoonbill release_package.json
```

Output:

```
warning: Detected additional column: /awards/relatedLots in parties table
warning: Detected additional column: /awards/relatedLots in parties table
warning: Detected additional column: /awards/relatedLots in parties table
warning: Detected additional column: /awards/relatedLots in parties table
warning: Detected additional column: /awards/relatedLots in parties table
warning: Detected additional column: /awards/relatedLots in parties table
warning: Detected additional column: /awards/relatedLots in parties table
warning: Detected additional column: /awards/relatedLots in parties table
warning: Detected additional column: /awards/relatedLots in parties table
warning: Detected additional column: /awards/relatedLots in parties table
...
```

Desired behavior (just warn once):

```
warning: Detected additional column: /awards/relatedLots in parties table
```

If there is a use case, we can add a CLI option to change the behavior to warn each time. This is similar to Python's options for warnings filters: https://docs.python.org/3/library/warnings.html#the-warnings-filter

Also, when there is a new warning, it causes the "Processed" progress bar to be repeated.

**Comment by jpmckinney** [comment]
By the way, do we need these warnings? What happens to the additional column? Is it omitted?

**Comment by yshalenyk** [comment]
We reduced logging level for this messages to DEBUG, so it should be easier on eyes now. But still could be enabled with `--verbosity DEBUG` option.

![image](https://user-images.githubusercontent.com/15928770/119796260-e5f6ae00-bee1-11eb-8b6a-707b8aa166e9.png)
