### ISSUE TITLE
Performance notes

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/spoonbill#77]
After applying #74 and #75, spoonbill can flatten a test file (Cyprus OpenTender data) in 45s, compared to Flatten Tool at 40s. (Before those PRs, it would take 65s.) **2021-05-26 Update:** Spoonbill is now 34s. Flatten Tool still about 40s.

Looking at this call graph:

* 59% of the time is spent in xlsxwriter (worksheet). The rest of the time is spent analyzing the file (24%) and flattening for writing (8%). Unless there is an option to make xlsxwriter faster, we need to focus on the others.
* `is_array` is called a lot and spends a lot of time in `sorted`. I tried using a `SortedDict` from [sortedcontainers](https://pypi.org/project/sortedcontainers/) but the time was actually worse. However, I think we can sort it once before flattening?
* We can maybe use `@functools.lru_cache(maxsize=None)` on more methods (if the additional memory is not significant).

![CY2](https://user-images.githubusercontent.com/26463/119203932-398c7600-ba62-11eb-8ddf-25c197061609.png)

**Comment by kindly** [comment]
From what I understand XLSXwriter is going to be slower than openpyxl in write only mode.  The problem with `write only mode` is that you have to write to one sheet at a time and can not swap between sheets.  Flattentool is optimised for this as it stores individual sheet data upfront (at the cost of writing the whole file again).  Flattentool could be a lot faster as this initial storage could be improved a lot with a better smaller on disk format, it was at about 20% faster when I used leveldb as the backend.

The difference with spoonbill is that writing one sheet at a time is more difficult, as before the analysis is done, there is not way to know what fields are in what sheets, so you can not analyse and store at the same time.  Possibly storing each sheet in another format before putting it into openpyxl would be faster.  This could be just it into CSV first and then into the XLSX in write only mode (with a few type conversions).  You could also potentially parralellize the CSV writing by having the writing in another thread to the processing (pontentially even one thread per sheet).

**Comment by jpmckinney** [comment]
The benchmarks are a few versions behind, but openpyxl seems slower even with write only mode: https://openpyxl.readthedocs.io/en/stable/performance.html

Benchmark code: https://foss.heptapod.net/openpyxl/openpyxl/-/snippets/66

**Comment by kindly** [comment]
@jpmckinney interesting.  Then I wonder if there is any cost in the context shifting from one sheet to another.  
I am not sure how the zipped XML works internally and if the libraries need to start copying data around i.e inserting stuff into the middle of an XML file or move files around in the zip. Such things would be what was is expensive and is why I assumed (possibly wrongly) "write only mode" would be faster.

When flattentool moved over to `write only mode` there seemed to be a bigger jump in performance than those betchmarks suggest but at the time I was more concerned about memory usage than performance.

**Comment by kindly** [comment]
Ran those benchmarks with 100% text which is closer to OCDS and got the following.

```
Versions:
python: 3.7.1
openpyxl: 3.0.7
xlsxwriter: 1.4.3

Dimensions:
    Rows = 1000
    Cols = 50
    Sheets = 5
    Proportion text = 1.00

Times:
    xlsxwriter            :   7.90
    xlsxwriter (optimised):   7.36
    openpyxl              :   6.02
    openpyxl (optimised)  :   6.07
```
With mostly numbers I got similar results as that page.

You also need lxml installed to make openpyxl faster.  

There is a bug in that test code that if you change the fill factor it does not actually change the percentage text as it does a modulo later.  However testing 100% is easy even though in OCDS it is probably more like 90%.

**Comment by jpmckinney** [comment]
Thanks for testing! Do both use a similar amount of memory?

**Comment by kindly** [comment]
It is hard to test memory without completely rewriting the bentchmark code.  I know openpyxl uses very little memory when I did this is flattentool.
Also I was wrong about `openpyxl` that you can switch between sheets in write only mode as I did a test of that.

**Comment by kindly** [comment]
> By the way, it looks like xlsxwriter writes XML "by hand" so it does not interact with a DOM.

Yep I saw that.  I think lxml will have the advantage of the string escaping checking being done in C libarary, which makes some sense why strings are faster and integers are not.

**Comment by jpmckinney** [comment]
When running Spoonbill vs Flatten Tool, Flatten Tool's memory usage looks much higher (maybe not due to openpyxl).

Also, the benchmark on my hardware is the other way around:

```
Versions:
python: 3.6.1
openpyxl: 3.0.7
xlsxwriter: 1.4.3

Dimensions:
    Rows = 1000
    Cols = 50
    Sheets = 5
    Proportion text = 1.00

Times:
    xlsxwriter            :   3.04
    xlsxwriter (optimised):   2.81
    openpyxl              :   3.96
    openpyxl (optimised)  :   3.48
```

**Comment by kindly** [comment]
@jpmckinney did you fix the profiling code from
```
 if not row % 10
```
to
```
 if not row % 1
```
to make sure it does all strings.

I am not sure why flattentool memory is higher but I am tested some large files and it definately plateaus.

I have also been experimenting with what happens if you write to all the sheets again with another 1000 lines using this gist:

https://gist.github.com/kindly/0a6e48829efe022e0b4e9a4008d7d8a2

For me the results are strange.

```
Versions:
python: 3.7.1
openpyxl: 3.0.7
xlsxwriter: 1.4.3

Dimensions:
    Rows = 1000
    Cols = 50
    Sheets = 5
    Proportion text = 2.00

Times:
    xlsxwriter            :   6.51
    xlsxwriter (optimised):   7.65
    openpyxl              :   7.07
    openpyxl (optimised)  :   6.15
```

**Comment by jpmckinney** [comment]
`if not row % 1` is 100% text. `if row % 10` is 90% text. At 90% text, the optimized versions are the same (xlsxwriter maybe even a bit faster). So for OCDS data I think both have similar performance.

**Comment by kindly** [comment]
Here is a notebook which runs Ubuntu 18.04:

https://colab.research.google.com/drive/194-gC2rR1c5vX__o9BAo0EcirEnkw0ku#scrollTo=ir8x3Iq15mSO

**Comment by kindly** [comment]
I have updated the above notebook with a more realistic test senario for spoonbill.

It writes 10 lines to each sheet and repeats this 1000 times rather than writing 10,000 rows to each sheet in order.  This at 90% text.

There is seems something up with xlsxwriter doing this in optimized mode making it 25% slower than "normal" mode and openpyxl write only mode.

To me it makes no sense that spoonbill is slower than flattentool as flattentool writes the whole file again which takes up around 1/3 of the time (even though it does the analysis then too).

**Comment by jpmckinney** [comment]
On my machine with that script, openpyxl (optimized) is sometime slower than non-optimized, and xlsxwriter is always faster non-optimized, and sometimes faster optimized. openpyxl calls the mode "optimized" but in xlsxwriter this just means "constant memory", so there is likely a RAM-CPU tradeoff.

**Comment by jpmckinney** [comment]
My recent runs of spoonbill with #74 and #75 are faster than flatten tool (there have been some recent commits), and there are some other potential quick wins as in the issue description. Quinta has not deliberately looked into performance improvements since the focus has been on functionality, so they might have other ideas at the algorithm-level.

**Comment by jpmckinney** [comment]
The python3 branch of xlsxwriter now seems to be consistently faster than openpyxl in every mode.
