### ISSUE TITLE
Handle single release/record

### ISSUE THREAD

**Issue by yshalenyk** [open-contracting/spoonbill#82]

**Comment by jpmckinney** [comment]
My understanding is that multiple releases/records works. `iter_file` ignores its `root` argument if `multiple_values=True`, i.e. the root element is assumed to be a release. https://github.com/open-contracting/spoonbill/pull/115

In the case that there is a single release/record, that `multiple_values=True` logic isn't applied, and instead the package-based logic is used.

I think this scenario (flattening a single release/record) is unlikely (a single release/record is pretty useless for data analysis), so I'll mark as wontfix. (The user will have to wrap their single release/record using ocdskit.)
